#ifndef _BITMAP_HPP
#define _BITMAP_HPP

/**
  * \brief compress every 8 bytes block into a 9 or less bytes block.
  * \param fileName - the string holding the name of the file to be compressed.
  * \param bitMap   - the vector with the list of the chars and its occurrences.
  * \param myFile   - the struct with the file information.
  * \return if the compression goes wrong then false, else, true
  */
bool compressBitMap (const char *fileName, std::vector<std::pair<int, unsigned char> > bitMap, FileInfo *myFile);

/**
  * \brief decompress the file generated by the function above.
  * \param fileName - the string holding the name of the file to be decompressed.
  * \param myFile   - the struct with the compressed file information, like the character compressed.
  * \return if the decompression goes wrong then false, else, true
  */
bool decompressBitMap (const char *fileName, FileInfo *myFile);

#endif
